# Generated by Django 6.0.2 on 2026-02-19 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SmartDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Örn: Salon Lambası, Mutfak Prizi', max_length=100, verbose_name='Cihaz Adı')),
                ('ip_address', models.GenericIPAddressField(help_text='Tasmota cihazın yerel IP adresi', protocol='IPv4', unique=True, verbose_name='IP Adresi')),
                ('room', models.CharField(choices=[('salon', 'Salon'), ('yatak_odasi', 'Yatak Odası'), ('mutfak', 'Mutfak'), ('banyo', 'Banyo'), ('koridor', 'Koridor'), ('balkon', 'Balkon'), ('ofis', 'Çalışma Odası'), ('diger', 'Diğer')], default='salon', max_length=50, verbose_name='Oda')),
                ('device_type', models.CharField(choices=[('switch', 'Anahtar / Röle'), ('light', 'Aydınlatma'), ('plug', 'Akıllı Priz'), ('sensor', 'Sensör')], default='switch', max_length=20, verbose_name='Cihaz Tipi')),
                ('is_active', models.BooleanField(default=True, help_text='Cihaz sisteme dahil mi?', verbose_name='Aktif')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='Son Görülme')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme')),
            ],
            options={
                'verbose_name': 'Akıllı Cihaz',
                'verbose_name_plural': 'Akıllı Cihazlar',
                'ordering': ['room', 'name'],
            },
        ),
    ]
