# Generated by Django 5.2.7 on 2026-02-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartdevice',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
