# Generated by Django 6.0.2 on 2026-02-20 20:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smart_home', '0003_smartdevice_owner_alter_smartdevice_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='smartdevice',
            name='ip_address',
            field=models.GenericIPAddressField(help_text='Tasmota cihazın yerel IP adresi', protocol='IPv4', verbose_name='IP Adresi'),
        ),
        migrations.AlterUniqueTogether(
            name='smartdevice',
            unique_together={('owner', 'ip_address')},
        ),
        migrations.CreateModel(
            name='DeviceShareRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(protocol='IPv4', verbose_name='IP Adresi')),
                ('device_name', models.CharField(max_length=100, verbose_name='Cihaz Adı')),
                ('room', models.CharField(max_length=50, verbose_name='Oda')),
                ('device_type', models.CharField(max_length=20, verbose_name='Cihaz Tipi')),
                ('status', models.CharField(choices=[('pending', 'Bekliyor'), ('approved', 'Onaylandı'), ('rejected', 'Reddedildi')], default='pending', max_length=10, verbose_name='Durum')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Sonuçlanma')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_share_requests', to=settings.AUTH_USER_MODEL, verbose_name='Cihaz Sahibi')),
                ('requester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_share_requests', to=settings.AUTH_USER_MODEL, verbose_name='İsteyen')),
            ],
            options={
                'verbose_name': 'Cihaz Paylaşım İsteği',
                'verbose_name_plural': 'Cihaz Paylaşım İstekleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
